### ISSUE TITLE
Todo List

### ISSUE THREAD

**Issue by t3chguy** [t3chguy/riot-static#1]
- [ ] Renderers for common events, e.g Images, HTML, Files etc
- [ ] Historical Member Info
- [ ] make Peeking more useful (pagination etc)
- [ ] investigate additional meta useful for spidering
- [ ] make cache invalidate after N requests or M minutes

**Comment by t3chguy** [comment]
don't backpaginate if has reached m.room.create

**Comment by t3chguy** [comment]
- [ ] filter out joins/parts by default but allow control over this.

**Comment by Ryuno-Ki** [comment]
Could you add a directory for the js files and add a line which loads an (possibly empty) JS file?

**Comment by t3chguy** [comment]
There are ***no*** js files, thats the whole point of this project

**Comment by Ryuno-Ki** [comment]
How do I have to interpret
> linkify-js style thing
then?

**Comment by t3chguy** [comment]
it'll be done server-side, what linkify-js does is parse the event body looking for links and making them clickable links, very simply done server side
